    Numpy 장점
    속도 빠르다
    편하고, 쉽다.
    C로 만들어졌다.
    
    빠른 이유 : 호모지니어스를 띄며 1열로 저장하고 strides 로 표현하기 때문에 빠르다.

## vectorization

- compile 기법
- vector 화 시킨다 (여러 개의 데이터를 하나로 묶어준다)
- CPU 자체에서 최적화를 지원해준다.
- for 구문을 쓰지 않는다(루프 안씀), 속도 느려지기 때문.
- 이터레이터,제너레이터, 컴프리헨션, 재귀함수, Higher Other Function(map, filter, reduce)

    1차원(Vector) 벡터는 방향이 없다고 보면 된다.
    2차원(Matrix)
    3차원(Tensor)
    N차원(ND array)

In [1]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
# factory method
# 기본적인 데이터구조를 만듬. 호모지니어스(장점 : 데이터가 뭐가 올 지 예측할 필요가 없어 속도가 빠르다.)
a = np.array(1)

In [5]:
a

array(1)

In [6]:
a = np.array([1,2])

In [7]:
a

array([1, 2])

In [8]:
a = np.array((1,2))

In [9]:
a

array([1, 2])

In [10]:
# nd : n 차원
type(a)

numpy.ndarray

In [11]:
# 2차원
a = np.array([[1,2],[3,4]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
# 3차원 (공백이 있다 : 데이터가 겹쳐져 있구나...)
a = np.array([[[1,2],[3,4]], [[1,2],[3,4]]])

In [16]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [18]:
n = np.ndarray(0) #호모지니어스. 

In [19]:
n

array([], dtype=float64)

In [20]:
# 문자열로 바뀌었다.
a = np.array(['1',2,3])

In [21]:
a
#                              < little  endian          //             > big endian

array(['1', '2', '3'], dtype='<U1')

In [24]:
n = np.ndarray([0,'1'])

TypeError: 'str' object cannot be interpreted as an integer

In [ ]:
인스턴스화 : factory method

    '__dict__' 가 적용이 안되면 vars() 가 나오지 않는다.

In [28]:
a = np.array([[1,2],[3,4]])

In [30]:
a.ndim

2

In [31]:
a.shape

(2, 2)

In [33]:
a.flags
# C --> [1 ,2], [3 ,4]
# F --> [1, 3], [2, 4]

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [36]:
# 원소의 개수
a.size

4

In [37]:
# 각 하나가 몇 bit 인가
a.itemsize

4

In [38]:
a.dtype

dtype('int32')

In [39]:
b = np.array([[1,2],[3,4]])

In [40]:
x = [1,2,3,4]
y = [2,3,4,5]

In [41]:
x+y

[1, 2, 3, 4, 2, 3, 4, 5]

In [42]:
# 원소끼리 계산함.
# element wise 방식
a+b

array([[2, 4],
       [6, 8]])

In [43]:
[a+b for a,b in zip(x,y)]

[3, 5, 7, 9]

내부구조는 1열로 구성되어있다.
Header(data-type)

In [44]:
# 2행 2열이다. 
a.strides

(8, 4)

----------------------------------------------

파이썬은 overflow가 없다. 많이 집어넣을 수가 있다.

_(언더바)
1. 앞에 언더바 한 개 붙을 때 : 관례상 privit
2. 앞에 언더바 두 개 붙을 때 : OP? mengling
3. __ __ : magic method, 
4. 관례상 필요없는 변수일 때. 
5. _( ) : 다국어 처리할 때
6. 이름 충돌을 피하기 위해. ex) string_

In [47]:
a = np.array([[1,2],[3,4]], dtype = 'u1')

In [52]:
len(np.sctypeDict)

152

In [55]:
# arange 기능
a = np.arange(10)

In [54]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# reshape() : 2행 5열로 바꿔줌.
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
# 값은 변하지 않았다.
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# axis == 0 이면 2,5 --> 결과 5개
a.sum()

45

In [74]:
%time sum(x for x in range(100000000))

Wall time: 9.04 s


4999999950000000

In [75]:
%time np.sum(np.arange(100000000))

Wall time: 339 ms


887459712

----------------------------------------------------

In [76]:
# shape : 행 열 정하기
a = np.zeros((3,4))

In [77]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
b = np.ones((3,3))

In [79]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
c = np.full((3,2),6)

In [83]:
c

array([[6, 6],
       [6, 6],
       [6, 6]])

In [84]:
# shape 만 가져와서 똑같은 행렬을 만들어줌
d = np.ones_like(a)

In [85]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
# 단위행렬 만들 때 : eye() , identity()
# shape 이 아니네... 정방행렬이기 때문.
b = np.eye(3)

In [88]:
c = np.identity(3)

In [89]:
#b = np.diau()
b = np.tri(3)

In [90]:
b

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [91]:
b = np.triu((3,3))

In [92]:
b

array([[3, 3],
       [0, 3]])

In [99]:
d = np.linspace(0,100)
d

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [98]:
e = np.logspace(1,100)
e

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [101]:
# empty : 쓰레기값
e = np.empty((4,2))
e

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.56119178e-321],
       [1.69118108e-306, 1.42420616e-306]])

---------------------------

In [103]:
a = np.arange(10).reshape(2,5)

In [104]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
# 특정 데이터 뽑기 : indexing, slicing, key
# a[1][3]

a[1,3]

8

In [106]:
a[:,3]

array([3, 8])

In [107]:
a = np.arange(27).reshape(3,3,3)

In [108]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [114]:
a[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [115]:
# ... : 전부 다 가져와라.
a[1,...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [116]:
a[:,:,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [118]:
a[1:,1:,1:]

array([[[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]]])

In [119]:
a = np.arange(10)

In [120]:
a[(a>3) & (a<8)]

array([4, 5, 6, 7])

In [121]:
a[(a>3) | (a<8)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [126]:
# Fancy Indexing
a[[-1,-2]]

array([9, 8])

In [127]:
a = np.arange(10).reshape(5,2)

In [128]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [131]:
a[[1,3]]

array([[2, 3],
       [6, 7]])

indexing, slicing 기법
- , 
- ... 
- 조건 
- 마스킹 
- fancy indexing

In [132]:
a = np.arange(25).reshape(5,5)

In [133]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [134]:
a[0]

array([0, 1, 2, 3, 4])

In [135]:
a[1,3:5]

array([8, 9])

In [136]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [138]:
a[-2:, -2:]

array([[18, 19],
       [23, 24]])

In [139]:
a[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [140]:
a[[1,2,4],[2,3,4]]

array([ 7, 13, 24])

In [141]:
a[3:, [0,1,3]]

array([[15, 16, 18],
       [20, 21, 23]])

In [142]:
mask = np.array([0,1,0,0,1], dtype=np.bool)

In [143]:
a[mask, 1]

array([ 6, 21])

In [172]:
b = np.nditer(a)

In [176]:
next(b)

array(3)

In [187]:
# vectorized function
def add_(a,b):
    return a+b

In [188]:
x = np.arange(5)
y = np.arange(5)

In [189]:
add_(x,y)

array([0, 2, 4, 6, 8])

In [190]:
x

array([0, 1, 2, 3, 4])

In [192]:
# Broadcasting (numpy 에서 부족한부분은 알아서 크기를 맞춰준다.)
3 + np.arange(10)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

--------------------------------

## ufunc

- universal function
- 절대값

In [194]:
abs(-1) # 파이썬 절대값.

1

In [195]:
np.abs(-1) # numpy 절대값.

1

In [196]:
# numpy 절대값 abs 는 리스트도 가능하다!
np.abs([-1,-5,-3])

array([1, 5, 3])

In [197]:
np.ceil([2,9,1,2,3,0.3])

array([2., 9., 1., 2., 3., 1.])

In [198]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [199]:
from scipy.special import factorial

In [203]:
factorial([3,4,5])

array([  6.,  24., 120.])

In [205]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x0000021077F1A4E0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [208]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
# 조건이 참이면 0 으로 바꾸고 아니면 1로 바꿔라
# where : 인덱스 뽑는 거 외에 데이터를 변경시키는 기능이 있다.
np.where(b>5, 0, 1)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [209]:
b[np.where(b>5)]

array([6, 7, 8, 9])

In [210]:
np.max(b)

9

In [211]:
# 가장 큰 수를 나타내는 인덱스를 반환한다.
np.argmax(b)

9

In [212]:
np.argmin(b)

0

In [214]:
b.argmin()

0

In [215]:
from numpy import pi

In [216]:
from math import pi as mpi

In [217]:
pi

3.141592653589793

In [218]:
mpi

3.141592653589793

In [219]:
pi == mpi

True

In [220]:
type(...)

ellipsis

In [224]:
dir(...)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [225]:
np.nan

nan

In [226]:
float('nan')

nan

In [227]:
np.nan == float('nan')

False

In [231]:
# 결과값이 없으면 None 과 같다. 이런 건 외워야한다는 것이었던 것이었다.
np.newaxis

-----------------------

In [232]:
a = np.arange(10).reshape(2,5)

In [233]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [235]:
b = a

In [236]:
# 만약 바뀌면 deep copy
a[0][0] = 100

In [237]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [238]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [239]:
c = b.copy()

In [240]:
# 파이썬 에서 copy() 하면 shallow copy
# numpy 에서는 deep copy
b[0][0] = -100

In [241]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [242]:
c

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [243]:
# numpy 에서 shallow copy 하려면 view() 하면 됨
c = b.view()

In [244]:
b[0][0] = 2300

In [245]:
c

array([[2300,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [246]:
b

array([[2300,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
# 원본을 보관하기 위해 copy 를 사용한다.