In [1]:
import time

In [2]:
time.time()

1563865177.6947994

In [3]:
import datetime

In [4]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'sys',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [5]:
from datetime import datetime, timedelta

In [6]:
a = datetime(2019,7,22)

In [7]:
b = timedelta(99)

In [8]:
a + b

datetime.datetime(2019, 10, 29, 0, 0)

In [9]:
a = datetime.strptime('2019-07-23', '%Y-%m-%d')

In [10]:
a

datetime.datetime(2019, 7, 23, 0, 0)

In [12]:
# numpy 는 타입을 변경할 수 있는 기능이 있다.
import numpy as np

In [13]:
a = np.array([1,2,3])

In [14]:
a

array([1, 2, 3])

In [15]:
a.dtype = np.int8

In [16]:
a

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0], dtype=int8)

In [17]:
a.dtype = 'int8'

In [18]:
a

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0], dtype=int8)

In [19]:
# astype : ~로 타입을 바꿔라
a.astype('float64')

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0.])